services:
  berichtsheft:
    build: .
    container_name: berichtsheft
    ports:
      - "0.0.0.0:8001:8000"
    env_file: .env
    environment:
      TZ: Europe/Berlin
    volumes:
      - ./data:/data
    restart: unless-stopped
